import Head from "next/head";
import Link from "next/link";

import { api } from "~/utils/api";

export default function Home() {
  const hello = api.post.hello.useQuery({ text: "from tRPC" });
  const post = api.post.getAll.useQuery()
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main >
        <div>
          <div>Post</div>
          <div>
            {post.data?.map((item) => (
              <div key={item.id} className="flex gap-3">
                <div>{item.id}</div>
                <div>{item.content}</div>
              </div>
            ))}
          </div>
        </div>
      </main>
    </>
  )
}
