import { useUser } from "@clerk/nextjs";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import { useState } from "react";
import CreatePostWizard from "~/components/createPostWizard";
import PostItem from "~/components/postItem";

import { api } from "~/utils/api";


export default function Home() {
  const [createUserForm, setCreateUserForm] = useState({
    email: 'test@gmail.com',
    password: '123456',
  })
  const userId = 1
  const createUserMutation = api.user.create.useMutation()
  const loginUser = api.user.login.useQuery({ email: createUserForm.email, password: createUserForm.password })

  const onCreateUser = async (user: { email: string, password: string }) => {
    try {
      await createUserMutation.mutateAsync({
        email: user.email,
        password: user.password,
      })
      // clear form
      // setFormCreateUser({
      //   name: '',
      //   email: ''
      // })
      // onGetAllUsers()
    } catch (error) {
      console.log(error)
    }
  }

  const onLogin = async () => {
    try {
      const res = await loginUser.refetch()
      if (res) {
        console.log('%cMyProject%cline:41%cres', 'color:#fff;background:#ee6f57;padding:3px;border-radius:2px', 'color:#fff;background:#1f3c88;padding:3px;border-radius:2px', 'color:#fff;background:rgb(161, 23, 21);padding:3px;border-radius:2px', res)
      }
    } catch (error) {
      console.log(error)

    }
  }
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* nav */}
      <div className="p-6 bg-blue-900">
        <div className="flex  justify-end gap-6">
          <Link href={'/'}>Home</Link>
          <Link href={`/restaurant/${userId}`}>My Restaurant</Link>
        </div>
      </div>

      <div className="border p-3">
        <strong>Create Account</strong>
        <div>
          <input type="text" placeholder="username" />
          <input type="text" placeholder="password" />
          <button onClick={() => onCreateUser({ email: createUserForm.email, password: createUserForm.password })}>Create</button>
        </div>
      </div>
      <div className="border p-3">
        <strong>Login</strong>
        <div>
          <input type="text" placeholder="username" />
          <input type="text" placeholder="password" />
          <button onClick={() => onLogin()}>Sign in</button>
        </div>
      </div>
    </>
  )
}
