import { useUser } from "@clerk/nextjs";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import CreatePostWizard from "~/components/createPostWizard";
import PostItem from "~/components/postItem";

import { api } from "~/utils/api";


export default function Home() {

  const { user } = useUser()
  const post = api.post.getAll.useQuery()
  console.log('%cMyProject%cline:13%cpost', 'color:#fff;background:#ee6f57;padding:3px;border-radius:2px', 'color:#fff;background:#1f3c88;padding:3px;border-radius:2px', 'color:#fff;background:rgb(179, 214, 110);padding:3px;border-radius:2px', post.data)
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* navbar */}
      <div className="flex justify-end p-3 bg-slate-800">
        {user ? (
          <div className="flex items-center gap-3">
            <div className="relative w-10 h-10 rounded-full overflow-hidden">
              <Image
                src={user.imageUrl}
                layout="fill"
                style={{ objectFit: 'cover' }}
                alt=""
              />
            </div>
            {user.fullName}</div>
        ) : ''}
      </div>
      <main className="px-6">
        <div>
          <CreatePostWizard />
        </div>
        <div>
          <div>Post</div>
          <div className="flex flex-col gap-3">
            {post.data?.map((item) => (
              <div key={item.post.id}>
                <PostItem data={item} />
              </div>
            ))}
          </div>
        </div>
      </main>
    </>
  )
}
